version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
  crawler:
    build: ./search_engine_crawler
    environment:
      - EXCLUDE_URLS=.*github.com
  ui:
    build: ./search_engine_ui
    container_name: ui
    ports:
      - '8000:8000'
  
  prometheus:
    build: ./monitoring
    container_name: 'prometheus'
  
  grafana:
    image: grafana/grafana
    container_name: 'grafana'
