{
 "title": "otus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "web_pages_served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "web_page_gen_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "web_page_gen_time_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Crawler pages parsed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "crawler_pages_parsed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "crawler_page_parse_time_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "crawler_page_parse_time_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "crawler_site_connection_time_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}