---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: kurs
  labels:
    app: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      name: crawler
      labels:
        app: crawler
    spec:
      hostname: crawler
      containers:
      - name: crawler
        image: daniilrostov/crawler:1.0
        name: crawler
        env:
        - name: EXCLUDE_URLS
          value: .*github.com
        - name: MONGO
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
